### ISSUE TITLE
Segmentation faults on tiny dummy inputs (possible race condition?)

### ISSUE THREAD

**Issue by hmusta** [splatlab/mantis#15]
When I was testing mantis on some dummy files, I noticed that it segfaults most of the time when I run it (at different times during execution), but it occasionally runs to completion.

The script below reproduces the issue (I've symlinked `squeakr-count` built from the exact branch and `mantis` to my data folder, but this issue also occurs when I call them in their build folders)

```
#/bin/bash

bzcat SRR403012.fastq.bz2 | head -n 8 > test.fq
./squeakr-count -f -k 12 -s 20 -t 1 test.fq
echo "test.fq_exact.ser 1" > inputs.lst
./mantis build -s 20 -i inputs.lst -o .
```
This results in the input fastq file
```
@SRR403012.1 HWUSI-EAS108E_0007:2:1:9625:985 length=49
GAAGGGTTAACTTAAGCGAGATCCNAGCAGAGAAGCAGGTCGAAGNNNN
+SRR403012.1 HWUSI-EAS108E_0007:2:1:9625:985 length=49
,,*).....@C@C@@C@C@##############################
@SRR403012.2 HWUSI-EAS108E_0007:2:1:10006:990 length=49
GCTTGTTTGGGAAGTGGCATTCATNGTGCTCCAGGGGCGGGTGGGNNNN
+SRR403012.2 HWUSI-EAS108E_0007:2:1:10006:990 length=49
#################################################
```

I have attached the log from 7 runs of the above script: [runlog.txt](https://github.com/splatlab/mantis/files/2228795/runlog.txt)

When I run the `mantis` command through `valgrind`, I notice several invalid reads and writes, but it runs to completion. I have attached the log: [valgrind.txt](https://github.com/splatlab/mantis/files/2228843/valgrind.txt)
Let me know if I can provide any other information or logs to help debug this.

Thanks!

**Comment by prashantpandey** [comment]
Hi @hmusta , we looked into the issue and the seg-fault is coming because of a race condition in async I/O callbacks.
We have fixed the issue and pushed it to master. Please try it now.

**Comment by hmusta** [comment]
Thanks for resolving this! I ran it again and it does indeed run to completion every time now.

I noticed that there is still an issue with memory leakage and `Conditional jump or move depends on uninitialised value(s)` warnings. I've attached a [new log](https://github.com/splatlab/mantis/files/2232625/valgrind2.txt) if you want to look into it further.
